Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Models/ErrorViewModel.cs
namespace Agendamento_de_Tarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Models/StatusTarefa.cs
namespace Agendamento_de_Tarefas.Models
{
    public enum StatusTarefa
    {
        Pendente = 0,
        EmAndamento = 1,
        Concluida = 2
    }
}

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Models/Tarefa.cs
namespace Agendamento_de_Tarefas.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public StatusTarefa Status{ get; set; }
    }
}

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Controllers/HomeController.cs
using System.Diagnostics;
using Agendamento_de_Tarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace Agendamento_de_Tarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Controllers/TarefaController.cs
using Agendamento_de_Tarefas.Context;
using Microsoft.AspNetCore.Mvc;
using Agendamento_de_Tarefas.Models;

namespace Agendamento_de_Tarefas.Controllers
{
    public class TarefaController : Controller
    {
        private readonly AgendaContext _context;

        public TarefaController(AgendaContext context)
        {
            _context = context;
        }

        public IActionResult Index(string filtro, string valor)
        {
            var tarefas = _context.Tarefas.AsQueryable();

            if (string.IsNullOrEmpty(filtro) || string.IsNullOrEmpty(valor))
                return View(tarefas.ToList());

            if (filtro == "Titulo")
                tarefas = tarefas.Where(t => t.Titulo.Contains(valor));

            if (filtro == "Data" && DateTime.TryParse(valor, out DateTime data))
                tarefas = tarefas.Where(t => t.Data.Date == data.Date);

            if (filtro == "Status" && Enum.TryParse<StatusTarefa>(valor, out var status))
                tarefas = tarefas.Where(t => t.Status == status);

            return View(tarefas.ToList());
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _context.Tarefas.Add(tarefa);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(tarefa);
        }

        public IActionResult Editar(int id)
        {
            var tarefa = _context.Tarefas.Find(id);

            if (tarefa == null) return RedirectToAction("Index");

            return View(tarefa);
        }

        [HttpPost]
        public IActionResult Editar(Tarefa tarefa)
        {
            var tarefaBanco = _context.Tarefas.Find(tarefa.Id);

            tarefaBanco.Titulo = tarefa.Titulo;
            tarefaBanco.Descricao = tarefa.Descricao;
            tarefaBanco.Data = tarefa.Data;
            tarefaBanco.Status = tarefa.Status;

            _context.Tarefas.Update(tarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var tarefa = _context.Tarefas.Find(id);

            if (tarefa == null) return RedirectToAction(nameof(Index));

            return View(tarefa);
        }

        public IActionResult Deletar(int id)
        {
            var tarefa = _context.Tarefas.Find(id);

            if (tarefa == null) return RedirectToAction(nameof(Index));

            _context.Tarefas.Remove(tarefa);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Bem Vindo";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Esse é um desafio de projeto feito utilizando o ASP.NET MVC e o Entity Framework. </p>
    <p> O desafio proposto é criar uma lista de tarefa realizando as quatro operações possiveis dentro de um CRUD. </p>
</div>

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agendamento_de_Tarefas</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Agendamento_de_Tarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agendamento de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="flex: 1" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Agendamento de Tarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Tarefa/Criar.cshtml
@model Tarefa

@{
    ViewData["Title"] = "Criar nova Tarefa";
}

<h1>@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" type="date" />
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<Agendamento_de_Tarefas.Models.StatusTarefa>()"></select>
            </div>

            <br />

            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />

<div>
    <a asp-action="Index">Voltar</a>
</div>

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Tarefa/Detalhes.cshtml
@model Tarefa

@{
    ViewData["Title"] = "Detalhes da tarefa";
}

<h1>Detalhes</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Id)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Id)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Data)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Status)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>

<a asp-action="Editar" asp-route-id="@Model.Id">Editar</a> |
<a asp-action="Index">Voltar</a>

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Tarefa/Editar.cshtml
@model Tarefa

@{
    ViewData["Title"] = "Editar Tabela";
}

<h1>@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" type="date"/>
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<Agendamento_de_Tarefas.Models.StatusTarefa>()"></select>
            </div>

            <br/>

            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />

<div>
    <a asp-action="Index">Voltar</a>
</div>

Formacao .NET Developer/Desafios De Projetos/trilha-net-api-desafio/Agendamento de Tarefas/Views/Tarefa/Index.cshtml
@model IEnumerable<Tarefa>

@{
    ViewData["Title"] = "Lista de Tarefas";
}

<h1>Tarefas</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
    <p class="mb-0">
        <a asp-action="Criar" class="btn btn-success">Nova Tarefa</a>
    </p>

    <form asp-action="Index" method="get" class="d-flex align-items-center gap-2 w-auto" method="get">
        <select name="filtro" class="form-select">
            <option value="Titulo">Título</option>
            <option value="Data">Data</option>
            <option value="Status">Status</option>
        </select>

        <div id="valorContainer" class="flex-grow-1 w-100">
            <input name="valor" class="form-control" />
        </div>

        <input type="submit" value="Filtrar" class="btn btn-primary" />
    </form>
</div>

<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>

            <th>Ações</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>

                <td>
                    @Html.DisplayFor(model => item.Titulo)
                </td>

                <td>
                    @Html.DisplayFor(model => item.Data)
                </td>

                <td>
                    @Html.DisplayFor(model => item.Status)
                </td>

                <td>
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id" onclick="return confirm('Não é possivel reverter essa ação deseja continuar?');">Deletar</a>
                </td>
            </tr>
        }
    </tbody>

</table>